/** Map display config - shared between /df-code and /team-find */

import type { DailyCodes } from '../services/deltaforce.scraper.js';

/** Path tới ảnh map */
export const ASSETS_PATH = './src/assets/img/map/';

/** Giới hạn mặc định cho /df-history */
export const MAX_HISTORY_LIMIT = 10;

/** Map info: display name and image filename */
export interface MapInfo {
  name: string;
  image: string;
}

/** Derive from DailyCodes so both types stay in sync */
export type MapKey = keyof DailyCodes;

/** Map display registry - keys match DailyCodes from scraper */
export const MAP_DISPLAY: Record<MapKey, MapInfo> = {
  'Đập Nước Zero': { name: 'Zero Dam', image: 'map_zero.png' },
  'Thung lũng Layali': { name: 'Layali', image: 'map_layali.png' },
  'Phố Cổ Brakkesh': { name: 'Brakkesh', image: 'map_brakkesh.png' },
  AZ3: { name: 'AZ3', image: 'map_az3.png' },
  'Trạm Không Gian': { name: 'Space City', image: 'map_spacecity.png' },
  'Ngục Giam Thủy Triều': { name: 'Tide Prison', image: 'map_tideprison.png' },
};

/** Difficulty levels for /team-find */
export type Difficulty = 'easy' | 'normal' | 'hard';

export interface DifficultyConfig {
  id: Difficulty;
  label: string;
  color: number;
}

export const DIFFICULTY_CONFIG: Record<Difficulty, DifficultyConfig> = {
  easy: { id: 'easy', label: 'Dễ', color: 0x57f287 },
  normal: { id: 'normal', label: 'Thường', color: 0xfee75c },
  hard: { id: 'hard', label: 'Khó', color: 0xed4245 },
};

/** Map → available modes mapping (controls dependent options) */
export const MAP_MODES: Record<MapKey, Difficulty[]> = {
  'Thung lũng Layali': ['easy'],
  'Đập Nước Zero': ['easy', 'normal'],
  'Phố Cổ Brakkesh': ['normal', 'hard'],
  AZ3: ['easy', 'normal'],
  'Trạm Không Gian': ['normal', 'hard'],
  'Ngục Giam Thủy Triều': ['hard'],
};

/** DF-history emoji IDs */
export const EMOJI_WIN = '<a:HoA:1512368174614446181>';
export const EMOJI_DEFEAT = '<:hom_xac:1514470840312401971>';
export const EMOJI_MONEY = '<:icon9De6T9unB:1514474246779306115>';
export const EMOJI_KILL = '<:kill:1514482180254990407>';

/** Map ID → display name mapping (extracted from maps_vn.js) */
export const MAP_NAMES: Record<number, string> = {
  2201: 'Đập Nước Zero - Dễ',
  2202: 'Đập nước Zero - Thường',
  2221: 'Đập Nước Zero - Tầng Hầm',
  2222: 'Đập Nước Zero - Doanh Trại',
  2223: 'Đập Nước Zero - TTHC',
  2212: 'Chiến Dịch Sinh Tồn, Đập Nước (Thường) - Solo',
  2232: 'Đập Nước Zero - Đêm Vô Tận',
  1901: 'Thung Lũng Layali - Dễ',
  1902: 'Thung Lũng Layali – Thường',
  1911: 'Thung Lũng Layali – Solo Dễ',
  1912: 'Thung Lũng Layali – Solo Thường',
  1921: 'Thung Lũng Layali – Khách Sạn Nữ Hoàng Lấp Lánh',
  1922: 'Thung lũng Layali - Trạm Radar',
  3901: 'Trạm Không Gian Haavk - Thường',
  3902: 'Trạm Không Gian Haavk - Khó',
  3921: 'Trạm Không Gian Haavk - Khu Vực Văn Phòng CEO',
  3922: 'Trạm Không Gian Haavk – Khu Vực Trung Tâm',
  8102: 'Phố Cổ Brakkesh - Thường',
  8103: 'Phố Cổ Brakkesh - Khó',
  8121: 'Brakkesh – Chợ',
  8122: 'Phố Cổ Brakkesh - Tháp Babel',
  8123: 'Brakkesh – Đỉnh Tháp',
  8802: 'Ngục Giam Thủy Triều – Thích Nghi',
  8803: 'Ngục Giam Thủy Triều – Khó',
  8821: 'Ngục Giam Thủy Triều – Khu Vực Trung Tâm',
  108: 'Chiếm Đóng - Chiến Hào Điện Gió',
  107: 'Công & Thủ – Chiến Hào Điện Gió',
  2401: 'Chiến Hào Điện Gió - Chiến Trường Thiết Giáp - PvE',
  605: 'Công & Thủ – Đại Đoàn Kết – Chiến Hào Điện Gió',
  127: 'Siêu Tốc - Chiến Hào Điện Gió',
  128: 'Vây Hãm – Chiến Hào Điện Gió',
  227: 'Chiến Trường Thiết Giáp – Chiến Hào Điện Gió',
  585: 'Loạn Chiến Shotgun – Chiến Hào Điện Gió',
  902: 'Chiến Hào Điện Gió – Tử Chiến',
  555: 'Uy Lực Bất Tận – Chiến Hào Điện Gió',
  561: 'Vũ Điệu Lôi Đình – Chiến Hào Điện Gió',
  579: 'Hỏa Chiến Tung Hoành – Chiến Hào',
  567: 'Xạ Tiễn Giao Tranh - Chiến Hào Điện Gió',
  1107: 'Xung Phong – C/T– Chiến Hào Điện Gió',
  966: 'May Mắn Mỉm Cười – Chiến Hào Điện Gió',
  971: 'Chiến Thuật Tử Chiến – Chiến Hào Điện Gió',
  34: 'Cứ Điểm Than Hồng – Chiếm Đóng',
  33: 'Công & Thủ - Cứ Điểm Than Hồng',
  2403: 'Cứ Điểm Than Hồng - Chiến Trường Thiết Giáp - PvE',
  602: 'Công & Thủ - Đại Đoàn Kết - Cứ Điểm Than Hồng',
  109: 'Cứ Điểm Than Hồng – Siêu Tốc',
  118: 'Vây Hãm – Cứ Điểm Than Hồng',
  119: 'Đồi Thép – Cứ Điểm Than Hồng',
  587: 'Loạn Chiến Shotgun - Cứ Điểm Than Hồng',
  903: 'Cứ Điểm Than Hồng – Tử Chiến',
  557: 'Uy Lực Bất Tận – Cứ Điểm Than Hồng',
  563: 'Vũ Điệu Lôi Đình – Cứ Điểm Than Hồng',
  581: 'Hỏa Chiến Tung Hoành – Cứ Điểm Than Hồng',
  569: 'Xạ Tiễn Giao Tranh – Cứ Điểm Than Hồng',
  1059: 'Nóng Chiến Thuật – Cứ Điểm Than Hồng',
  959: 'Điểm Nóng – Cứ Điểm Than Hồng',
  980: 'Cường Hóa – Cứ Điểm Than Hồng',
  956: 'Quân đoàn Thiết Giáp – Cứ Điểm Than Hồng',
  900: 'Chiếm Cờ – Cứ Điểm Than Hồng',
  965: 'May Mắn Mỉm Cười – Cứ Điểm Than Hồng',
  972: 'Chiến Thuật Tử Chiến – Cứ Điểm Than Hồng',
  112: 'Chiếm Đóng – Điểm Dừng Tàu Hỏa',
  111: 'Công & Thủ - Điểm Dừng Tàu Hỏa',
  2404: 'Điểm Dừng Tàu Hỏa – Chiến Trường Thiết Giáp – PvE – Mới',
  606: 'Công & Thủ – Đại Đoàn Kết – Điểm Dừng Tàu Hỏa',
  526: 'Thiết Giáp – Điểm Dừng Tàu Hỏa',
  583: 'Loạn Chiến Shotgun – Điểm Dừng Tàu Hỏa',
  904: 'Điểm Dừng Tàu Hỏa – Tử Chiến',
  553: 'Uy Lực Bất Tận – Điểm Dừng Tàu Hỏa',
  559: 'Vũ Điệu Lôi Đình – Điểm Dừng Tàu Hỏa',
  577: 'Hỏa Chiến Tung Hoành – Điểm Dừng Tàu Hỏa',
  565: 'Xạ Tiễn Giao Tranh – Điểm Dừng Tàu Hỏa',
  958: 'Quân đoàn Thiết Giáp – Điểm Dừng Tàu Hỏa',
  967: 'May Mắn Mỉm Cười – Điểm Dừng Tàu Hỏa',
  973: 'Chiến Thuật Tử Chiến – Điểm Dừng Tàu Hỏa',
  103: 'Chiếm Đóng – Pháo Đài Bất Bại',
  54: 'Công và Thủ - Pháo Đài Bất Bại',
  2402: 'Pháo Đài Bất Bại - Chiến Trường Thiết Giáp - PvE',
  601: 'Công & Thủ - Đại Đoàn Kết - Pháo Đài Bất Bại',
  105: 'Siêu Tốc – Pháo Đài Bất Bại',
  116: 'Vây Hãm - Pháo Đài Bất Bại',
  117: 'Đồi Thép - Pháo Đài Bất Bại',
  586: 'Loạn Chiến Shotgun – Pháo Đài Bất Bại',
  901: 'Pháo Đài Bất Bại – Tử Chiến',
  551: 'Càn Quét Diện Rộng – Pháo Đài Bất Bại',
  556: 'Uy Lực Bất Tận – Pháo Đài Bất Bại',
  562: 'Vũ Điệu Lôi Đình – Pháo Đài Bất Bại',
  580: 'Hỏa Chiến Tung Hoành – Tăng Lực Độ',
  568: 'Xạ Tiễn Giao Tranh – Tăng Lên',
  957: 'Quân đoàn Thiết Giáp – Pháo Đài Bất Bại',
  970: 'Chiến Thuật Tử Chiến – Pháo Đài Bất Bại',
  122: 'Chiếm Đóng - Phía Trên Đập Nước',
  121: 'Công & Thủ - Phía Trên Đập Nước',
  2406: 'Phía Trên Đập Nước – Chiếm Đóng – PvE – Mới',
  584: 'Loạn Chiến Shotgun – Phía Trên Đập Nước',
  514: 'Phía Trên Đập Nước – Tử Chiến',
  554: 'Uy Lực Bất Tận – Phía Trên Đập Nước',
  560: 'Vũ Điệu Lôi Đình – Phía Trên Đập Nước',
  566: 'Xạ Tiễn Giao Tranh – Phía Trên Đập Nước',
  969: 'Chiến Thuật Tử Chiến – Phía Trên Đập Nước',
  152: 'Địa Tầng Đổ Vỡ – Chiếm Đóng',
  151: 'Địa Tầng Đổ Vỡ – Công & Thủ',
  611: 'Công & Thủ – Đại Đoàn Kết – Địa Tầng Đổ Vỡ',
  552: 'Đột Kích Khoảng Trống – Địa Tầng Đổ Vỡ',
  951: 'Uy Lực Bất Tận – Địa Tầng Đổ Vỡ',
  961: 'Điểm Nóng – Địa Tầng Đổ Vỡ',
  946: 'Tử Chiến - Địa Tầng Đổ Vỡ',
  975: 'Chiến Thuật Tử Chiến – Địa Tầng Đổ Vỡ',
  303: 'Chiếm Đóng – Lốc Xoáy',
  302: 'Công & Thủ – Lốc Xoáy',
  608: 'Công & Thủ – Đại Đoàn Kết – Lốc Xoáy',
  1302: 'Xung Phong – C/T – Lốc Xoáy',
  887: 'Cướp Cờ – Lốc Xoáy',
  139: 'Di Sản Bất Diệt – Chiếm Đóng',
  138: 'Di Sản Bất Diệt – Công & Thủ',
  949: 'Uy Lực Bất Tận – Quảng Trường Kỷ Niệm',
  948: 'Xạ Tiễn Giao Tranh – Quảng Trường Kỷ Niệm',
  1062: 'Điểm Nóng Chiến Thuật – Di Sản Bất Diệt',
  962: 'Điểm Nóng – Di Sản Bất Diệt',
  947: 'Tử Chiến - Di Sản Bất Diệt',
  609: 'Công & Thủ - Đại Đoàn Kết - Di Sản Bất Diệt',
  979: 'Cường Hóa – Di Sản Bất Diệt',
  996: 'Quân đoàn Thiết Giáp – Kỷ Niệm',
  968: 'May Mắn Mỉm Cười – Di Sản Bất Diệt',
  146: 'Chiếm Đóng – Dư Chấn',
  145: 'Công & Thủ – Dư Chấn',
  610: 'Công/Thủ - Đại Đoàn Kết - Dư Chấn',
  997: 'Quân đoàn Thiết Giáp – Dư Chấn',
  963: 'Điểm Nóng – Dư Chấn',
  964: 'Tử Chiến – Dư Chấn',
  1063: 'Điểm Nóng Chiến Thuật – Dư Chấn',
  978: 'Cường Hóa – Dư Chấn',
  977: 'Chiến Thuật Tử Chiến – Dư Chấn',
  550: 'Trận Chiến Hải Đảo – Không Kích Yếm Trợ',
  312: 'Chiến Trường Toàn Diện – Chiếm Đóng – Kênh Đào Akh',
  311: 'Chiến Trường Toàn Diện – Công & Thủ – Kênh Đào Akh',
  885: 'Tử Chiến – Kênh Đào Akh',
  612: 'Công/Thủ - Đại Đoàn Kết - Kênh Đào Akh',
  889: 'Cướp Cờ – Kênh Đào Akh',
  981: 'Chiến Thuật Tử Chiến – Kênh Đào Akh',
  950: 'Xạ Tiễn Giao Tranh – Địa Tầng Đổ Vỡ',
  1061: 'Nóng Chiến Thuật – Địa Tầng Đổ Vỡ',
  114: 'Chiếm Đóng – Trạm Nghiên Cứu Ngầm',
  113: 'Công & Thủ - Trạm Nghiên Cứu Ngầm',
  2407: 'Trạm Nghiên Cứu Ngầm – Chiếm Đóng – PvE – Mới',
  124: 'Siêu Tốc – Trạm Nghiên Cứu Ngầm',
  999: 'Điểm Nóng – Trạm Nghiên Cứu Ngầm',
  210: 'Chiếm Đóng - Phố Cảng Quân Sự',
  75: 'Công & Thủ - Phố Cảng Quân Sự',
  2405: 'Phố Cảng Quân Sự – Chiếm Đóng – PvE – Mới',
  603: 'Công & Thủ - Đại Đoàn Kết - Phố Cảng Quân Sự',
  213: 'Phố Cảng Quân Sự - Siêu Tốc',
  126: 'Vây Hãm - Phố Cảng Quân Sự',
  588: 'Loạn Chiến Shotgun – Phố Cảng Quân Sự',
  906: 'Phố Cảng Quân Sự – Tử Chiến',
  558: 'Uy Lực Bất Tận – Phố Cảng Quân Sự',
  564: 'Vũ Điệu Lôi Đình – Phố Cảng Quân Sự',
  582: 'Hỏa Chiến Tung Hoành – Phố Cảng Quân Sự',
  570: 'Xạ Tiễn Giao Tranh – Phố Cảng Quân Sự',
  8901: 'AZ3 – Dễ',
  8902: 'AZ3 – Thường',
  8921: 'AZ3 - Viện Hàn Lâm Khoa Học',
  8923: 'AZ3 - Lò Phản Ứng Nước Áp Lực',
  985: 'Chiến Hào Điện Gió - Không Gian Cuồng Bạo',
  984: 'Cứ Điểm Than Hồng - Không Gian Cuồng Bạo',
  445: 'Kẻ Săn Gió - Cứ Điểm Than Hồng',
  700: 'Kiểm Soát - Cứ Điểm Than Hồng',
  986: 'Điểm Dừng Tàu Hỏa - Không Gian Cuồng Bạo',
  1002: 'Truy Lùng Cao Thủ - Pháo Đài Bất Bại',
  706: 'Kiểm Soát - Địa Tầng Đổ Vỡ',
  1000: 'Truy Lùng Át Chủ Bài - Địa Tầng Đổ Vỡ',
  1003: 'Truy Lùng Át Chủ Bài – Lốc Xoáy',
  446: 'Kẻ Săn Gió - Lốc Xoáy',
  703: 'Kiểm Soát - Di Sản Bất Diệt',
  1001: 'Cuộc Săn Át – Đài Kỷ Niệm',
  172: 'Chiếm Đóng – Đấu Trường La Mã',
  171: 'Công/Thủ – Đấu Trường La Mã',
  982: 'Tử Chiến – Đấu Trường La Mã',
  613: 'Công/Thủ – Đại Đoàn Kết – Đấu Trường La Mã',
  983: 'Tử Chiến – Đấu Trường La Mã',
  2858: 'Chiến Trường Thiết Giáp - Đấu Trường',
  447: 'Kẻ Săn Gió - Đấu Trường La Mã',
  702: 'Kiểm Soát - Đấu Trường La Mã',
  8922: 'AZ3 - Lò Phản Ứng Trung Tâm',
  436: 'Siêu Cường Hóa – Chiến Hào Điện Gió',
  437: 'Siêu Cường Hóa – Cứ Điểm Than Hồng',
  884: 'Lốc Xoáy - Hợp Đồng Cuồng Phong',
  435: 'Siêu Cường Hóa – Di Sản Bất Diệt',
  434: 'Đấu Trường La Mã - Siêu Cường Hóa',
  262: 'Chiếm Đóng - The Mog',
  261: 'Tấn Công/Phòng Thủ - The Mog',
  433: 'Tử Chiến Đồng Đội - The Mog',
  614: 'Công & Thủ - Đại Đoàn Kết - The Mog',
  438: 'Cường Hóa - The Mog',
};

/** SOL rank choices for /team-find — matches /df-stats display */
export const TEAM_FIND_RANKS: { name: string; value: string }[] = [
  { name: 'Đồng III', value: 'Đồng III' },
  { name: 'Đồng II', value: 'Đồng II' },
  { name: 'Đồng I', value: 'Đồng I' },
  { name: 'Bạc III', value: 'Bạc III' },
  { name: 'Bạc II', value: 'Bạc II' },
  { name: 'Bạc I', value: 'Bạc I' },
  { name: 'Vàng IV', value: 'Vàng IV' },
  { name: 'Vàng III', value: 'Vàng III' },
  { name: 'Vàng II', value: 'Vàng II' },
  { name: 'Vàng I', value: 'Vàng I' },
  { name: 'Bạch Kim IV', value: 'Bạch Kim IV' },
  { name: 'Bạch Kim III', value: 'Bạch Kim III' },
  { name: 'Bạch Kim II', value: 'Bạch Kim II' },
  { name: 'Bạch Kim I', value: 'Bạch Kim I' },
  { name: 'Kim Cương V', value: 'Kim Cương V' },
  { name: 'Kim Cương IV', value: 'Kim Cương IV' },
  { name: 'Kim Cương III', value: 'Kim Cương III' },
  { name: 'Kim Cương II', value: 'Kim Cương II' },
  { name: 'Kim Cương I', value: 'Kim Cương I' },
  { name: 'Cao Thủ V', value: 'Cao Thủ V' },
  { name: 'Cao Thủ IV', value: 'Cao Thủ IV' },
  { name: 'Cao Thủ III', value: 'Cao Thủ III' },
  { name: 'Cao Thủ II', value: 'Cao Thủ II' },
  { name: 'Cao Thủ I', value: 'Cao Thủ I' },
  { name: 'Thách Đấu DF', value: 'Thách Đấu DF' },
];
